# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 18:46
from __future__ import unicode_literals

import carousel.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('slide', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('lecture', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=100)),
                ('docfile', models.FileField(upload_to=carousel.models.user_directory_path)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
