# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 20:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=100)),
                ('path', models.FileField(upload_to='media/')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
