# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='slide',
            field=models.IntegerField(default=0),
        ),
    ]
