# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='path',
            new_name='docfile',
        ),
    ]
