# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_auto_20180115_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carousel.Presentation'),
            preserve_default=False,
        ),
    ]
