# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_postcomment_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
    ]
